/*删除主键*/
ALTER TABLE CUSTOMES
	DROP PRIMARY KEY;
ALTER TABLE CUSTOMES
	MODIFY PRIMARY KEY(ID,NAME);

ALTER TABLE CUSTOMES
	ADD CONSTRAINT PK_ID PRIMARY KEY(ID);
/*删除约束PK_ID，但是报错*/
ALTER TABLE CUSTOMES
	DROP CONSTRAINT PK_ID;

/*创建外键表*/
CREATE TABLE ORDERS(
	ID INT NOT NULL,
	DATE DATETIME,
	CUSTOME_ID INT REFERENCES CUSTOMES(ID),
	AMOUNT DOUBLE,
	PRIMARY KEY(ID)
);


/*check约束*/
ALTER TABLE CUSTOMES
	MODIFY AGE INT NOT NULL CHECK(AGE >=18);

/*增加索引*/
CREATE INDEX index_customes_age ON CUSTOMES(AGE);

/*删除索引*/
ALTER TABLE CUSTOMES
	DROP INDEX index_customes_age;


SELECT 1 % -20;
SELECT CURRENT_TIMESTAMP AS TT;
SHOW DATABASE;
DESC CUSTOMES;

/*SQL从现有表创建表*/
CREATE TABLE NEW_CUSTOMES AS
	SELECT *
	FROM CUSTOMES;

DROP TABLE NEW_CUSTOMES;

/*添加一行数据，再次从现有表创建表*/
INSERT INTO CUSTOMES (ID,NAME,AGE,ADDRESS,SALARY)
	VALUES(1, 'A', 25, 'XI\'AN', 20000.00);

/*SQL从现有表创建表*/
CREATE TABLE NEW_CUSTOMES2 AS
	SELECT ID
	FROM CUSTOMES;

/*删除表中的记录*/
DELETE FROM CUSTOMES
	WHERE ID = 1;
/*删除表中所有记录*/
DELETE FROM CUSTOMES;

/*创建新表*/
CREATE TABLE CUSTOMERS AS
	SELECT * 
	FROM CUSTOMES;
DELETE FROM CUSTOMERS;
/*初始化表*/
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );


SELECT * FROM CUSTOMERS
	WHERE SALARY > 1000;

SELECT NAME AS TT
	FROM CUSTOMERS
	WHERE SALARY > 3000;


/*更新记录*/
UPDATE CUSTOMERS
	SET SALARY = 9000
	WHERE AGE >25 OR ID < 3;

SELECT * FROM CUSTOMERS;


/*like 语句*/

SELECT * FROM CUSTOMERS
	WHERE SALARY LIKE '%00%';

/*取前几个*/
SELECT * FROM CUSTOMERS
	LIMIT 3
	WHERE SALARY LIKE '%00';

/*ORDER BY 需在GROUP BY 之后*/
SELECT * FROM CUSTOMERS
	ORDER BY NAME DESC;
/*必须选出需要GROUP BY的属性*/
SELECT NAME, ID, COUNT(ID) AS TT
	FROM CUSTOMERS
	GROUP BY NAME,ID
	ORDER BY NAME DESC;
ALTER TABLE CUSTOMERS
	DROP PRIMARY KEY
INSERT INTO CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY)
	VALUES(2, 'Khilan', '32', 'Ahmedabad', 9000.00);
/*去重DISTINCT*/
SELECT DISTINCT NAME,ID FROM CUSTOMERS;

/*自定义排序结果*/
SELECT * FROM CUSTOMERS
	ORDER BY
(
CASE NAME
	WHEN 'KAUSHIK' THEN 1
	ELSE 100
END
) ASC, NAME ASC, SALARY DESC;

INSERT INTO ORDERS (ID,DATE, CUSTOME_ID, AMOUNT)
	VALUES(101, NOW(),1, 5000);

/*当前日期函数*/
SELECT NOW(); 

/*JOIN联接*/
SELECT CUSTOMERS.ID, NAME, AGE,AMOUNT
	FROM CUSTOMERS, ORDERS
	WHERE CUSTOMERS.ID = ORDERS.CUSTOME_ID;



SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS
	WHERE ID LIKE '%1';

